FROM node:22-alpine3.19

RUN mkdir /app
WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./

RUN npm install

COPY src/ src/

RUN npx prisma generate --schema=./src/model

CMD ["npm", "run", "start:prod"]
