FROM node:22-alpine3.19

RUN mkdir /app
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY src/ src/

RUN npx prisma generate --schema=./src/model/schema.prisma

CMD ["npm", "run", "localdev"]