FROM node:22-alpine3.19

RUN mkdir /app
WORKDIR /app

COPY ./express/package.json ./express/package-lock.json ./
RUN npm install

COPY express/src/ src/

#RUN npm run prisma:generate

#CMD ["npm", "run", "dev"]
